[mcp_servers.codebase-memory]
args = [ ]
command = "codebase-memory-mcp"
enabled = true
env = { }

[mcp_servers.context7]
enabled = true
url = "https://mcp.context7.com/mcp"

[mcp_servers.playwright]
args = [ "@playwright/mcp@0.0.81" ]
command = "npx"
enabled = true
env = { }
